---
# included file

- name: Jenkins RPM Key
  environment:
    http_proxy: "{{ jenkins2_rpm_key_proxy_url }}"
    HTTP_PROXY: "{{ jenkins2_rpm_key_proxy_url }}"
    https_proxy: "{{ jenkins2_rpm_key_proxy_url }}"
    HTTPS_PROXY: "{{ jenkins2_rpm_key_proxy_url }}"
  rpm_key:
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    validate_certs: "{{ jenkins2_rpm_key_validate_certs }}"
    state: present
  become: yes

- name: Jenkins YUM Repository
  yum_repository:
    name: jenkinsrepo
    description: Jenkins YUM Repository
    baseurl: http://pkg.jenkins.io/redhat
    proxy: "{{ jenkins2_rpm_key_proxy_url | default('_none_', true) }}"
    gpgcheck: yes
    state: present
  become: yes

- name: Jenkins Installation
  yum:
    name: "{{ jenkins2_version }}"
    disable_gpg_check: "{{ jenkins2_disable_gpg_check }}"
    state: present
  become: yes
